2019-11-18 10:36:05,988 ERROR: Exception on /index [GET] [in c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Michael.Mistarz\python_laptop\flask\flask-tutorial\app\routes.py", line 19, in index
    form = PostForm()
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask_wtf\form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\wtforms\form.py", line 272, in __init__
    super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\wtforms\form.py", line 52, in __init__
    field = meta.bind_field(self, unbound_field, options)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\wtforms\meta.py", line 27, in bind_field
    return unbound_field.bind(form=form, **options)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\wtforms\fields\core.py", line 353, in bind
    return self.field_class(*self.args, **kw)
TypeError: __init__() got an unexpected keyword argument 'validtors'
2019-11-18 10:36:08,314 ERROR: Exception on /explore [GET] [in c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Michael.Mistarz\python_laptop\flask\flask-tutorial\app\routes.py", line 144, in explore
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2019-11-18 10:37:36,066 ERROR: Exception on /index [GET] [in c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Michael.Mistarz\python_laptop\flask\flask-tutorial\app\routes.py", line 19, in index
    form = PostForm()
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask_wtf\form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\wtforms\form.py", line 272, in __init__
    super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\wtforms\form.py", line 52, in __init__
    field = meta.bind_field(self, unbound_field, options)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\wtforms\meta.py", line 27, in bind_field
    return unbound_field.bind(form=form, **options)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\wtforms\fields\core.py", line 353, in bind
    return self.field_class(*self.args, **kw)
TypeError: __init__() got an unexpected keyword argument 'validtors'
2019-11-18 10:38:08,040 INFO: Microblog startup [in C:\Users\Michael.Mistarz\python_laptop\flask\flask-tutorial\app\__init__.py:41]
2019-11-18 10:38:10,047 ERROR: Exception on /index [GET] [in c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Michael.Mistarz\python_laptop\flask\flask-tutorial\app\routes.py", line 28, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
